name: Production Deployment

on:
  workflow_call:
    inputs:
      jira-keys:
        description: 'Enter the Jira Keys that are ready merged in this release.'
        required: true
        default: false
        type: string
    secrets:
      URL:
        required: true
      TOKEN:
        required: true

jobs:
  jira_deploy_prod:
      runs-on: ubuntu-latest

      steps:
      - name: Deploy to Production Jira
        run: |
          echo "github.event_name: ${{github.event_name}}"
          echo "github.ref: ${{github.ref}}"
          echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
          echo "Deploying to Production..."
      
      - name: Failed Jira Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV

      - name: Parse Jira Keys from All Commits
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: false
          parse-all-commits: true
          commit-message: ${{inputs.jira-keys}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}'
          CLIENT_SECRET: ${{ secrets.JIRA_CLIENT_SECRET }}

      - name: Confirm Deploy State and Jira Key Values
        if: always()
        run: |
          echo "DEPLOY_STATE: ${{env.DEPLOY_STATE}}"
          echo "Jira Keys: ${{steps.jira_keys.outputs.jira-keys}}"
          
      - name: test
        run: |
          echo '$CLIENT_ID'
          echo '$CLIENT_SECRET'
      
      - name: Push Deployment Info to Jira
        if: steps.jira_keys.outputs.jira-keys != ''
        id: push_deployment_info_to_jira
        uses: HighwayThree/jira-upload-deployment-info@master
        with:
          cloud-instance-base-url: 'https://minnek.atlassian.net'
          client-id: '${{ secrets.JIRA_CLIENT_ID }}'
          client-secret: '${{ secrets.JIRA_CLIENT_SECRET }}'
          deployment-sequence-number: '${{ github.run_id }}'
          update-sequence-number: '${{ github.run_id }}'
          issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
          display-name: "Deployment to Production"
          url: "${{github.event.repository.url}}/actions/runs/${{github.run_id}}"
          description: "Action for Deployment to Production"
          last-updated: '${{github.event.head_commit.timestamp}}'
          label: 'Production Deployment'
          state: '${{env.DEPLOY_STATE}}'
          pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
          pipeline-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
          pipeline-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
          environment-id: 'prod'
          environment-display-name: 'Production'
          environment-type: 'production'
