name: Grunt Theme Check

on:
  workflow_call:

jobs:
  grunt_check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Stencil CLI Dependency
      run: npm install -g @bigcommerce/stencil-cli

    - name: Install Theme Dependencies
      run: npm ci

    - name: Grunt Check - Stylelint/ESlint/Jest
      run: npx grunt check

    - name: Validate Theme Bundles - Config/Schema/Size
      run: npx stencil bundle --name bundle
